### ISSUE TITLE
What is the detailed definition of beta(x)?

### ISSUE THREAD

**Issue by larenzhang** [alexgain/cna-icml2020#1]
In your codes, you use the weighted acts to calculate the linear slope. Why should we do this?
``` python
  C = np.array([np.ones(len(acts)),np.arange(1,len(acts)+1)]).transpose()
  Cf = np.linalg.inv((C.T).dot(C)).dot(C.T)
  Cf = threshold(Cf)
  Cf = Cf[1,:]

  S = 0
  for j in range(len(Cf)):
      S += acts[j]*Cf[j]
```

**Comment by alexgain** [comment]
Cf is the (X^T X)^(-1) X^T matrix from ordinary least squares (https://en.wikipedia.org/wiki/Linear_least_squares). Here, y are the activation values. We ignore the intercept value (the first row of Cf) of the linear regression and only care about the slope value (which is the second row of Cf, i.e. Cf[1,:]).

EDIT: To be clear, given a depth L network, we are performing a linear regression via Ordinary Least Squares on the tuples (i, a_i), where i = 1, ..., L and a_i denotes the sum of the activation values at depth i. We are recovering the slope and intercept coefficients of this regression and only returning the slope.
